// <auto-generated />
using System;
using Cmms.Modules.Assets.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cmms.Modules.Assets.Infrastructure.Migrations
{
    [DbContext(typeof(AssetsDbContext))]
    partial class AssetsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("assets")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cmms.Modules.Assets.Domain.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Criticality")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("criticality");

                    b.Property<Guid?>("CurrentLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_location_id");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Model")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedTag")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("normalized_tag");

                    b.Property<Guid?>("ParentAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_asset_id");

                    b.Property<Guid>("QrLocator")
                        .HasColumnType("uuid")
                        .HasColumnName("qr_locator");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("row_version");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("serial_number");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tag");

                    b.HasKey("Id")
                        .HasName("pk_assets");

                    b.HasAlternateKey("SiteId", "Id")
                        .HasName("ak_assets_site_id_id");

                    b.HasIndex("NormalizedTag")
                        .IsUnique()
                        .HasDatabaseName("ix_assets_normalized_tag");

                    b.HasIndex("QrLocator")
                        .IsUnique()
                        .HasDatabaseName("ix_assets_qr_locator");

                    b.HasIndex("SiteId", "CurrentLocationId")
                        .HasDatabaseName("ix_assets_site_id_current_location_id");

                    b.HasIndex("SiteId", "ParentAssetId")
                        .HasDatabaseName("ix_assets_site_id_parent_asset_id");

                    b.ToTable("assets", "assets", t =>
                        {
                            t.HasCheckConstraint("ck_assets_criticality", "criticality IN ('A', 'B', 'C')");

                            t.HasCheckConstraint("ck_assets_normalized_tag", "normalized_tag = upper(btrim(tag))");

                            t.HasCheckConstraint("ck_assets_not_own_parent", "parent_asset_id IS NULL OR parent_asset_id <> id");

                            t.HasCheckConstraint("ck_assets_status", "status IN ('InService', 'OutOfService', 'Retired')");
                        });
                });

            modelBuilder.Entity("Cmms.Modules.Assets.Domain.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_location_id");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("row_version");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.HasKey("Id")
                        .HasName("pk_locations");

                    b.HasAlternateKey("SiteId", "Id")
                        .HasName("ak_locations_site_id_id");

                    b.HasIndex("SiteId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_locations_site_id_code");

                    b.HasIndex("SiteId", "ParentLocationId")
                        .HasDatabaseName("ix_locations_site_id_parent_location_id");

                    b.ToTable("locations", "assets", t =>
                        {
                            t.HasCheckConstraint("ck_locations_code_normalized", "code = upper(btrim(code))");

                            t.HasCheckConstraint("ck_locations_not_own_parent", "parent_location_id IS NULL OR parent_location_id <> id");
                        });
                });

            modelBuilder.Entity("Cmms.Modules.Assets.Domain.Asset", b =>
                {
                    b.HasOne("Cmms.Modules.Assets.Domain.Location", null)
                        .WithMany()
                        .HasForeignKey("SiteId", "CurrentLocationId")
                        .HasPrincipalKey("SiteId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_assets_locations_site_id_current_location_id");

                    b.HasOne("Cmms.Modules.Assets.Domain.Asset", null)
                        .WithMany()
                        .HasForeignKey("SiteId", "ParentAssetId")
                        .HasPrincipalKey("SiteId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_assets_assets_site_id_parent_asset_id");
                });

            modelBuilder.Entity("Cmms.Modules.Assets.Domain.Location", b =>
                {
                    b.HasOne("Cmms.Modules.Assets.Domain.Location", null)
                        .WithMany()
                        .HasForeignKey("SiteId", "ParentLocationId")
                        .HasPrincipalKey("SiteId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_locations_locations_site_id_parent_location_id");
                });
#pragma warning restore 612, 618
        }
    }
}
