// <auto-generated />
using System;
using Cmms.Modules.IdentityAccess.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cmms.Modules.IdentityAccess.Infrastructure.Migrations
{
    [DbContext(typeof(IdentityAccessDbContext))]
    partial class IdentityAccessDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identity_access")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cmms.Modules.IdentityAccess.Domain.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("users", "identity_access");
                });

            modelBuilder.Entity("Cmms.Modules.IdentityAccess.Domain.CompanyRoleAssignment", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("RoleCode")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("role_code");

                    b.Property<DateTimeOffset>("AssignedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at_utc");

                    b.HasKey("UserId", "RoleCode")
                        .HasName("pk_company_role_assignments");

                    b.HasIndex("RoleCode")
                        .HasDatabaseName("ix_company_role_assignments_role_code");

                    b.ToTable("company_role_assignments", "identity_access", t =>
                        {
                            t.HasCheckConstraint("ck_company_role_assignments_admin_only", "role_code = 'Admin'");
                        });
                });

            modelBuilder.Entity("Cmms.Modules.IdentityAccess.Domain.PermissionDefinition", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.HasKey("Code")
                        .HasName("pk_permission_definitions");

                    b.ToTable("permission_definitions", "identity_access");

                    b.HasData(
                        new
                        {
                            Code = "users.manage"
                        },
                        new
                        {
                            Code = "sites.manage"
                        },
                        new
                        {
                            Code = "assets.create"
                        },
                        new
                        {
                            Code = "assets.edit"
                        },
                        new
                        {
                            Code = "assets.criticality.change"
                        },
                        new
                        {
                            Code = "assets.read"
                        },
                        new
                        {
                            Code = "requests.create"
                        },
                        new
                        {
                            Code = "requests.read.own"
                        },
                        new
                        {
                            Code = "requests.read.all"
                        },
                        new
                        {
                            Code = "requests.convert"
                        },
                        new
                        {
                            Code = "requests.reject"
                        },
                        new
                        {
                            Code = "requests.cancel.own"
                        },
                        new
                        {
                            Code = "workorders.create"
                        },
                        new
                        {
                            Code = "workorders.plan"
                        },
                        new
                        {
                            Code = "workorders.schedule"
                        },
                        new
                        {
                            Code = "workorders.prioritize"
                        },
                        new
                        {
                            Code = "workorders.selfclaim"
                        },
                        new
                        {
                            Code = "workorders.assign"
                        },
                        new
                        {
                            Code = "workorders.reassign"
                        },
                        new
                        {
                            Code = "workorders.unassign"
                        },
                        new
                        {
                            Code = "workorders.read.assigned"
                        },
                        new
                        {
                            Code = "workorders.read.all"
                        },
                        new
                        {
                            Code = "workorders.execute"
                        },
                        new
                        {
                            Code = "workorders.complete"
                        },
                        new
                        {
                            Code = "workorders.close"
                        },
                        new
                        {
                            Code = "workorders.reopen"
                        },
                        new
                        {
                            Code = "workorders.cancel"
                        },
                        new
                        {
                            Code = "plans.manage"
                        },
                        new
                        {
                            Code = "plans.read"
                        },
                        new
                        {
                            Code = "costs.view"
                        },
                        new
                        {
                            Code = "audit.read.own"
                        },
                        new
                        {
                            Code = "audit.read.all"
                        },
                        new
                        {
                            Code = "audit.export"
                        },
                        new
                        {
                            Code = "attachments.read"
                        },
                        new
                        {
                            Code = "attachments.write"
                        },
                        new
                        {
                            Code = "attachments.unlink"
                        });
                });

            modelBuilder.Entity("Cmms.Modules.IdentityAccess.Domain.RoleDefinition", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("scope");

                    b.HasKey("Code")
                        .HasName("pk_role_definitions");

                    b.ToTable("role_definitions", "identity_access");

                    b.HasData(
                        new
                        {
                            Code = "Admin",
                            Scope = "Company"
                        },
                        new
                        {
                            Code = "Planner",
                            Scope = "Site"
                        },
                        new
                        {
                            Code = "Technician",
                            Scope = "Site"
                        },
                        new
                        {
                            Code = "Requester",
                            Scope = "Site"
                        });
                });

            modelBuilder.Entity("Cmms.Modules.IdentityAccess.Domain.RolePermission", b =>
                {
                    b.Property<string>("RoleCode")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("role_code");

                    b.Property<string>("PermissionCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("permission_code");

                    b.Property<string>("ResourcePredicate")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("resource_predicate");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("scope");

                    b.HasKey("RoleCode", "PermissionCode")
                        .HasName("pk_role_permissions");

                    b.HasIndex("PermissionCode")
                        .HasDatabaseName("ix_role_permissions_permission_code");

                    b.ToTable("role_permissions", "identity_access");

                    b.HasData(
                        new
                        {
                            RoleCode = "Admin",
                            PermissionCode = "users.manage",
                            Scope = "CompanyGlobal"
                        },
                        new
                        {
                            RoleCode = "Admin",
                            PermissionCode = "sites.manage",
                            Scope = "CompanyGlobal"
                        },
                        new
                        {
                            RoleCode = "Admin",
                            PermissionCode = "assets.create",
                            Scope = "AllSites"
                        },
                        new
                        {
                            RoleCode = "Admin",
                            PermissionCode = "assets.edit",
                            Scope = "AllSites"
                        },
                        new
                        {
                            RoleCode = "Admin",
                            PermissionCode = "assets.criticality.change",
                            Scope = "AllSites"
                        },
                        new
                        {
                            RoleCode = "Admin",
                            PermissionCode = "assets.read",
                            Scope = "AllSites"
                        },
                        new
                        {
                            RoleCode = "Admin",
                            PermissionCode = "requests.create",
                            Scope = "AllSites"
                        },
                        new
                        {
                            RoleCode = "Admin",
                            PermissionCode = "requests.read.own",
                            Scope = "OwnRecord"
                        },
                        new
                        {
                            RoleCode = "Admin",
                            PermissionCode = "requests.read.all",
                            Scope = "AllSites"
                        },
                        new
                        {
                            RoleCode = "Admin",
                            PermissionCode = "requests.convert",
                            Scope = "AllSites"
                        },
                        new
                        {
                            RoleCode = "Admin",
                            PermissionCode = "requests.reject",
                            Scope = "AllSites"
                        },
                        new
                        {
                            RoleCode = "Admin",
                            PermissionCode = "requests.cancel.own",
                            Scope = "OwnRecord"
                        },
                        new
                        {
                            RoleCode = "Admin",
                            PermissionCode = "workorders.create",
                            Scope = "AllSites"
                        },
                        new
                        {
                            RoleCode = "Admin",
                            PermissionCode = "workorders.plan",
                            Scope = "AllSites"
                        },
                        new
                        {
                            RoleCode = "Admin",
                            PermissionCode = "workorders.schedule",
                            Scope = "AllSites"
                        },
                        new
                        {
                            RoleCode = "Admin",
                            PermissionCode = "workorders.prioritize",
                            Scope = "AllSites"
                        },
                        new
                        {
                            RoleCode = "Admin",
                            PermissionCode = "workorders.selfclaim",
                            Scope = "AllSites"
                        },
                        new
                        {
                            RoleCode = "Admin",
                            PermissionCode = "workorders.assign",
                            Scope = "AllSites"
                        },
                        new
                        {
                            RoleCode = "Admin",
                            PermissionCode = "workorders.reassign",
                            Scope = "AllSites"
                        },
                        new
                        {
                            RoleCode = "Admin",
                            PermissionCode = "workorders.unassign",
                            Scope = "AllSites"
                        },
                        new
                        {
                            RoleCode = "Admin",
                            PermissionCode = "workorders.read.assigned",
                            Scope = "OwnAssignment"
                        },
                        new
                        {
                            RoleCode = "Admin",
                            PermissionCode = "workorders.read.all",
                            Scope = "AllSites"
                        },
                        new
                        {
                            RoleCode = "Admin",
                            PermissionCode = "workorders.execute",
                            Scope = "AllSites"
                        },
                        new
                        {
                            RoleCode = "Admin",
                            PermissionCode = "workorders.complete",
                            Scope = "AllSites"
                        },
                        new
                        {
                            RoleCode = "Admin",
                            PermissionCode = "workorders.close",
                            Scope = "AllSites"
                        },
                        new
                        {
                            RoleCode = "Admin",
                            PermissionCode = "workorders.reopen",
                            Scope = "AllSites"
                        },
                        new
                        {
                            RoleCode = "Admin",
                            PermissionCode = "workorders.cancel",
                            Scope = "AllSites"
                        },
                        new
                        {
                            RoleCode = "Admin",
                            PermissionCode = "plans.manage",
                            Scope = "AllSites"
                        },
                        new
                        {
                            RoleCode = "Admin",
                            PermissionCode = "plans.read",
                            Scope = "AllSites"
                        },
                        new
                        {
                            RoleCode = "Admin",
                            PermissionCode = "costs.view",
                            Scope = "AllSites"
                        },
                        new
                        {
                            RoleCode = "Admin",
                            PermissionCode = "audit.read.own",
                            Scope = "OwnRecord"
                        },
                        new
                        {
                            RoleCode = "Admin",
                            PermissionCode = "audit.read.all",
                            Scope = "AllSites"
                        },
                        new
                        {
                            RoleCode = "Admin",
                            PermissionCode = "audit.export",
                            Scope = "AllSites"
                        },
                        new
                        {
                            RoleCode = "Admin",
                            PermissionCode = "attachments.read",
                            ResourcePredicate = "inherit_parent_authorization",
                            Scope = "ParentResource"
                        },
                        new
                        {
                            RoleCode = "Admin",
                            PermissionCode = "attachments.write",
                            ResourcePredicate = "inherit_parent_authorization",
                            Scope = "ParentResource"
                        },
                        new
                        {
                            RoleCode = "Admin",
                            PermissionCode = "attachments.unlink",
                            ResourcePredicate = "inherit_parent_authorization",
                            Scope = "ParentResource"
                        },
                        new
                        {
                            RoleCode = "Planner",
                            PermissionCode = "assets.create",
                            Scope = "MemberSite"
                        },
                        new
                        {
                            RoleCode = "Planner",
                            PermissionCode = "assets.edit",
                            Scope = "MemberSite"
                        },
                        new
                        {
                            RoleCode = "Planner",
                            PermissionCode = "assets.criticality.change",
                            Scope = "MemberSite"
                        },
                        new
                        {
                            RoleCode = "Planner",
                            PermissionCode = "assets.read",
                            Scope = "MemberSite"
                        },
                        new
                        {
                            RoleCode = "Planner",
                            PermissionCode = "requests.create",
                            Scope = "MemberSite"
                        },
                        new
                        {
                            RoleCode = "Planner",
                            PermissionCode = "requests.read.own",
                            Scope = "OwnRecord"
                        },
                        new
                        {
                            RoleCode = "Planner",
                            PermissionCode = "requests.read.all",
                            Scope = "MemberSite"
                        },
                        new
                        {
                            RoleCode = "Planner",
                            PermissionCode = "requests.convert",
                            Scope = "MemberSite"
                        },
                        new
                        {
                            RoleCode = "Planner",
                            PermissionCode = "requests.reject",
                            Scope = "MemberSite"
                        },
                        new
                        {
                            RoleCode = "Planner",
                            PermissionCode = "requests.cancel.own",
                            Scope = "OwnRecord"
                        },
                        new
                        {
                            RoleCode = "Planner",
                            PermissionCode = "workorders.create",
                            Scope = "MemberSite"
                        },
                        new
                        {
                            RoleCode = "Planner",
                            PermissionCode = "workorders.plan",
                            Scope = "MemberSite"
                        },
                        new
                        {
                            RoleCode = "Planner",
                            PermissionCode = "workorders.schedule",
                            Scope = "MemberSite"
                        },
                        new
                        {
                            RoleCode = "Planner",
                            PermissionCode = "workorders.prioritize",
                            Scope = "MemberSite"
                        },
                        new
                        {
                            RoleCode = "Planner",
                            PermissionCode = "workorders.selfclaim",
                            Scope = "MemberSite"
                        },
                        new
                        {
                            RoleCode = "Planner",
                            PermissionCode = "workorders.assign",
                            Scope = "MemberSite"
                        },
                        new
                        {
                            RoleCode = "Planner",
                            PermissionCode = "workorders.reassign",
                            Scope = "MemberSite"
                        },
                        new
                        {
                            RoleCode = "Planner",
                            PermissionCode = "workorders.unassign",
                            Scope = "MemberSite"
                        },
                        new
                        {
                            RoleCode = "Planner",
                            PermissionCode = "workorders.read.assigned",
                            Scope = "OwnAssignment"
                        },
                        new
                        {
                            RoleCode = "Planner",
                            PermissionCode = "workorders.read.all",
                            Scope = "MemberSite"
                        },
                        new
                        {
                            RoleCode = "Planner",
                            PermissionCode = "workorders.execute",
                            Scope = "MemberSite"
                        },
                        new
                        {
                            RoleCode = "Planner",
                            PermissionCode = "workorders.complete",
                            Scope = "MemberSite"
                        },
                        new
                        {
                            RoleCode = "Planner",
                            PermissionCode = "workorders.close",
                            Scope = "MemberSite"
                        },
                        new
                        {
                            RoleCode = "Planner",
                            PermissionCode = "workorders.reopen",
                            Scope = "MemberSite"
                        },
                        new
                        {
                            RoleCode = "Planner",
                            PermissionCode = "workorders.cancel",
                            Scope = "MemberSite"
                        },
                        new
                        {
                            RoleCode = "Planner",
                            PermissionCode = "plans.manage",
                            Scope = "MemberSite"
                        },
                        new
                        {
                            RoleCode = "Planner",
                            PermissionCode = "plans.read",
                            Scope = "MemberSite"
                        },
                        new
                        {
                            RoleCode = "Planner",
                            PermissionCode = "costs.view",
                            Scope = "MemberSite"
                        },
                        new
                        {
                            RoleCode = "Planner",
                            PermissionCode = "audit.read.own",
                            Scope = "OwnRecord"
                        },
                        new
                        {
                            RoleCode = "Planner",
                            PermissionCode = "audit.read.all",
                            Scope = "MemberSite"
                        },
                        new
                        {
                            RoleCode = "Planner",
                            PermissionCode = "audit.export",
                            Scope = "MemberSite"
                        },
                        new
                        {
                            RoleCode = "Technician",
                            PermissionCode = "assets.read",
                            Scope = "MemberSite"
                        },
                        new
                        {
                            RoleCode = "Technician",
                            PermissionCode = "requests.create",
                            Scope = "MemberSite"
                        },
                        new
                        {
                            RoleCode = "Technician",
                            PermissionCode = "requests.read.own",
                            ResourcePredicate = "created_by_self",
                            Scope = "OwnRecord"
                        },
                        new
                        {
                            RoleCode = "Technician",
                            PermissionCode = "requests.cancel.own",
                            ResourcePredicate = "created_by_self_and_status_new",
                            Scope = "OwnRecord"
                        },
                        new
                        {
                            RoleCode = "Technician",
                            PermissionCode = "workorders.selfclaim",
                            ResourcePredicate = "unassigned_and_open",
                            Scope = "MemberSite"
                        },
                        new
                        {
                            RoleCode = "Technician",
                            PermissionCode = "workorders.read.assigned",
                            ResourcePredicate = "assignee_id_is_self",
                            Scope = "OwnAssignment"
                        },
                        new
                        {
                            RoleCode = "Technician",
                            PermissionCode = "workorders.execute",
                            ResourcePredicate = "assignee_id_is_self",
                            Scope = "OwnAssignment"
                        },
                        new
                        {
                            RoleCode = "Technician",
                            PermissionCode = "workorders.complete",
                            ResourcePredicate = "assignee_id_is_self",
                            Scope = "OwnAssignment"
                        },
                        new
                        {
                            RoleCode = "Technician",
                            PermissionCode = "plans.read",
                            Scope = "MemberSite"
                        },
                        new
                        {
                            RoleCode = "Technician",
                            PermissionCode = "audit.read.own",
                            ResourcePredicate = "actor_or_assigned_work_is_self",
                            Scope = "OwnRecord"
                        },
                        new
                        {
                            RoleCode = "Requester",
                            PermissionCode = "assets.read",
                            ResourcePredicate = "limited_asset_fields",
                            Scope = "MemberSite"
                        },
                        new
                        {
                            RoleCode = "Requester",
                            PermissionCode = "requests.create",
                            Scope = "MemberSite"
                        },
                        new
                        {
                            RoleCode = "Requester",
                            PermissionCode = "requests.read.own",
                            ResourcePredicate = "created_by_self",
                            Scope = "OwnRecord"
                        },
                        new
                        {
                            RoleCode = "Requester",
                            PermissionCode = "requests.cancel.own",
                            ResourcePredicate = "created_by_self_and_status_new",
                            Scope = "OwnRecord"
                        },
                        new
                        {
                            RoleCode = "Requester",
                            PermissionCode = "audit.read.own",
                            ResourcePredicate = "own_requests_only",
                            Scope = "OwnRecord"
                        },
                        new
                        {
                            RoleCode = "Planner",
                            PermissionCode = "attachments.read",
                            ResourcePredicate = "inherit_parent_authorization",
                            Scope = "ParentResource"
                        },
                        new
                        {
                            RoleCode = "Planner",
                            PermissionCode = "attachments.write",
                            ResourcePredicate = "inherit_parent_authorization",
                            Scope = "ParentResource"
                        },
                        new
                        {
                            RoleCode = "Planner",
                            PermissionCode = "attachments.unlink",
                            ResourcePredicate = "inherit_parent_authorization",
                            Scope = "ParentResource"
                        },
                        new
                        {
                            RoleCode = "Technician",
                            PermissionCode = "attachments.read",
                            ResourcePredicate = "inherit_parent_authorization",
                            Scope = "ParentResource"
                        },
                        new
                        {
                            RoleCode = "Technician",
                            PermissionCode = "attachments.write",
                            ResourcePredicate = "inherit_parent_authorization",
                            Scope = "ParentResource"
                        },
                        new
                        {
                            RoleCode = "Technician",
                            PermissionCode = "attachments.unlink",
                            ResourcePredicate = "inherit_parent_authorization",
                            Scope = "ParentResource"
                        },
                        new
                        {
                            RoleCode = "Requester",
                            PermissionCode = "attachments.read",
                            ResourcePredicate = "inherit_parent_authorization",
                            Scope = "ParentResource"
                        },
                        new
                        {
                            RoleCode = "Requester",
                            PermissionCode = "attachments.write",
                            ResourcePredicate = "inherit_parent_authorization",
                            Scope = "ParentResource"
                        },
                        new
                        {
                            RoleCode = "Requester",
                            PermissionCode = "attachments.unlink",
                            ResourcePredicate = "inherit_parent_authorization",
                            Scope = "ParentResource"
                        });
                });

            modelBuilder.Entity("Cmms.Modules.IdentityAccess.Domain.Site", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("row_version");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_zone");

                    b.HasKey("Id")
                        .HasName("pk_sites");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_sites_code");

                    b.ToTable("sites", "identity_access");
                });

            modelBuilder.Entity("Cmms.Modules.IdentityAccess.Domain.SiteMembership", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<DateTimeOffset>("AssignedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("role_code");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("row_version");

                    b.HasKey("UserId", "SiteId")
                        .HasName("pk_site_memberships");

                    b.HasIndex("RoleCode")
                        .HasDatabaseName("ix_site_memberships_role_code");

                    b.HasIndex("SiteId", "RoleCode", "IsActive")
                        .HasDatabaseName("ix_site_memberships_site_id_role_code_is_active");

                    b.ToTable("site_memberships", "identity_access", t =>
                        {
                            t.HasCheckConstraint("ck_site_memberships_site_roles_only", "role_code IN ('Planner', 'Technician', 'Requester')");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_claims_user_id");

                    b.ToTable("user_claims", "identity_access");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_logins_user_id");

                    b.ToTable("user_logins", "identity_access");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_user_tokens");

                    b.ToTable("user_tokens", "identity_access");
                });

            modelBuilder.Entity("Cmms.Modules.IdentityAccess.Domain.CompanyRoleAssignment", b =>
                {
                    b.HasOne("Cmms.Modules.IdentityAccess.Domain.RoleDefinition", null)
                        .WithMany()
                        .HasForeignKey("RoleCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_company_role_assignments_role_definitions_role_code");

                    b.HasOne("Cmms.Modules.IdentityAccess.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_company_role_assignments_users_user_id");
                });

            modelBuilder.Entity("Cmms.Modules.IdentityAccess.Domain.RolePermission", b =>
                {
                    b.HasOne("Cmms.Modules.IdentityAccess.Domain.PermissionDefinition", null)
                        .WithMany()
                        .HasForeignKey("PermissionCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permission_definitions_permission_code");

                    b.HasOne("Cmms.Modules.IdentityAccess.Domain.RoleDefinition", null)
                        .WithMany()
                        .HasForeignKey("RoleCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_role_definitions_role_code");
                });

            modelBuilder.Entity("Cmms.Modules.IdentityAccess.Domain.SiteMembership", b =>
                {
                    b.HasOne("Cmms.Modules.IdentityAccess.Domain.RoleDefinition", null)
                        .WithMany()
                        .HasForeignKey("RoleCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_site_memberships_role_definitions_role_code");

                    b.HasOne("Cmms.Modules.IdentityAccess.Domain.Site", null)
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_site_memberships_sites_site_id");

                    b.HasOne("Cmms.Modules.IdentityAccess.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_site_memberships_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Cmms.Modules.IdentityAccess.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_claims_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Cmms.Modules.IdentityAccess.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_logins_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Cmms.Modules.IdentityAccess.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_tokens_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
