<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Cmms.BuildingBlocks\Cmms.BuildingBlocks.csproj" />
    <ProjectReference Include="..\Modules\IdentityAccess\IdentityAccess.csproj" />
    <ProjectReference Include="..\Modules\Assets\Assets.csproj" />
    <ProjectReference Include="..\Modules\Audit\Audit.csproj" />
    <ProjectReference Include="..\Modules\MaintenanceRequests\MaintenanceRequests.csproj" />
    <ProjectReference Include="..\Modules\WorkManagement\WorkManagement.csproj" />
    <ProjectReference Include="..\Modules\PreventiveMaintenance\PreventiveMaintenance.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
