// <auto-generated />
using System;
using Cmms.Modules.PreventiveMaintenance.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cmms.Modules.PreventiveMaintenance.Infrastructure.Migrations
{
    [DbContext(typeof(PreventiveMaintenanceDbContext))]
    partial class PreventiveMaintenanceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("preventive_maintenance")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cmms.Modules.PreventiveMaintenance.Domain.MaintenancePlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActiveOccurrenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("active_occurrence_id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<int>("GenerationLeadTimeDays")
                        .HasColumnType("integer")
                        .HasColumnName("generation_lead_time_days");

                    b.Property<int>("IntervalDays")
                        .HasColumnType("integer")
                        .HasColumnName("interval_days");

                    b.Property<DateTimeOffset>("NextDueAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_due_at_utc");

                    b.Property<string>("RecurrenceType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("recurrence_type");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("row_version");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_maintenance_plans");

                    b.HasAlternateKey("SiteId", "Id")
                        .HasName("ak_maintenance_plans_site_id_id");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("ix_maintenance_plans_site_id");

                    b.HasIndex("Status", "NextDueAtUtc")
                        .HasDatabaseName("ix_maintenance_plans_status_next_due_at_utc");

                    b.ToTable("maintenance_plans", "preventive_maintenance", t =>
                        {
                            t.HasCheckConstraint("ck_maintenance_plans_interval_days", "interval_days > 0");

                            t.HasCheckConstraint("ck_maintenance_plans_lead_time", "generation_lead_time_days >= 0");

                            t.HasCheckConstraint("ck_maintenance_plans_recurrence_type", "recurrence_type IN ('Fixed', 'Floating')");

                            t.HasCheckConstraint("ck_maintenance_plans_status", "status IN ('Active', 'Paused')");
                        });
                });

            modelBuilder.Entity("Cmms.Modules.PreventiveMaintenance.Domain.MaintenancePlanOccurrence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("GeneratedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at_utc");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<DateTimeOffset>("ScheduledForUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_for_utc");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_order_id");

                    b.HasKey("Id")
                        .HasName("pk_maintenance_plan_occurrences");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("ix_maintenance_plan_occurrences_site_id");

                    b.HasIndex("WorkOrderId")
                        .IsUnique()
                        .HasDatabaseName("ix_maintenance_plan_occurrences_work_order_id");

                    b.HasIndex("PlanId", "ScheduledForUtc")
                        .IsUnique()
                        .HasDatabaseName("ix_maintenance_plan_occurrences_plan_id_scheduled_for_utc");

                    b.ToTable("maintenance_plan_occurrences", "preventive_maintenance");
                });

            modelBuilder.Entity("Cmms.Modules.PreventiveMaintenance.Domain.MaintenancePlanOccurrence", b =>
                {
                    b.HasOne("Cmms.Modules.PreventiveMaintenance.Domain.MaintenancePlan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_maintenance_plan_occurrences_maintenance_plans_plan_id");
                });
#pragma warning restore 612, 618
        }
    }
}
