// <auto-generated />
using System;
using Cmms.Modules.MaintenanceRequests.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cmms.Modules.MaintenanceRequests.Infrastructure.Migrations
{
    [DbContext(typeof(MaintenanceRequestsDbContext))]
    [Migration("20260903160209_InitialMaintenanceRequests")]
    partial class InitialMaintenanceRequests
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("maintenance_requests")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cmms.Modules.MaintenanceRequests.Domain.MaintenanceRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<Guid?>("ConvertedWorkOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("converted_work_order_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("priority");

                    b.Property<string>("RejectedReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("rejected_reason");

                    b.Property<DateTimeOffset?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at_utc");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("row_version");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_requests");

                    b.HasAlternateKey("SiteId", "Id")
                        .HasName("ak_requests_site_id_id");

                    b.HasIndex("ConvertedWorkOrderId")
                        .IsUnique()
                        .HasDatabaseName("ix_requests_converted_work_order_id")
                        .HasFilter("converted_work_order_id IS NOT NULL");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_requests_created_by_user_id");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("ix_requests_site_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_requests_status");

                    b.ToTable("requests", "maintenance_requests", t =>
                        {
                            t.HasCheckConstraint("ck_requests_asset_or_location", "asset_id IS NOT NULL OR location_id IS NOT NULL");

                            t.HasCheckConstraint("ck_requests_priority", "priority IN ('P1', 'P2', 'P3', 'P4')");

                            t.HasCheckConstraint("ck_requests_status", "status IN ('New', 'Converted', 'Rejected', 'Cancelled')");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
