// <auto-generated />
using System;
using Cmms.Modules.Attachments.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cmms.Modules.Attachments.Infrastructure.Migrations
{
    [DbContext(typeof(AttachmentsDbContext))]
    partial class AttachmentsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("attachments")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cmms.Modules.Attachments.Domain.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ByteSize")
                        .HasColumnType("bigint")
                        .HasColumnName("byte_size");

                    b.Property<string>("CleanStorageKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("clean_storage_key");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("ParentResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_resource_id");

                    b.Property<string>("ParentResourceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("parent_resource_type");

                    b.Property<int>("PixelHeight")
                        .HasColumnType("integer")
                        .HasColumnName("pixel_height");

                    b.Property<int>("PixelWidth")
                        .HasColumnType("integer")
                        .HasColumnName("pixel_width");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<DateTimeOffset?>("UnlinkedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("unlinked_at_utc");

                    b.Property<Guid>("UploadIntentId")
                        .HasColumnType("uuid")
                        .HasColumnName("upload_intent_id");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_attachments");

                    b.HasIndex("CleanStorageKey")
                        .IsUnique()
                        .HasDatabaseName("ix_attachments_clean_storage_key");

                    b.HasIndex("UploadIntentId")
                        .IsUnique()
                        .HasDatabaseName("ix_attachments_upload_intent_id");

                    b.HasIndex("ParentResourceType", "ParentResourceId")
                        .HasDatabaseName("ix_attachments_parent_resource_type_parent_resource_id");

                    b.ToTable("attachments", "attachments");
                });

            modelBuilder.Entity("Cmms.Modules.Attachments.Domain.AttachmentUploadIntent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DeclaredContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("declared_content_type");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<long>("MaxBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("max_bytes");

                    b.Property<string>("OriginalFileNameForDisplay")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_file_name_for_display");

                    b.Property<Guid>("ParentResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_resource_id");

                    b.Property<string>("ParentResourceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("parent_resource_type");

                    b.Property<string>("QuarantineKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("quarantine_key");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<long?>("UploadedByteCount")
                        .HasColumnType("bigint")
                        .HasColumnName("uploaded_byte_count");

                    b.HasKey("Id")
                        .HasName("pk_upload_intents");

                    b.HasIndex("QuarantineKey")
                        .IsUnique()
                        .HasDatabaseName("ix_upload_intents_quarantine_key");

                    b.HasIndex("ParentResourceType", "ParentResourceId")
                        .HasDatabaseName("ix_upload_intents_parent_resource_type_parent_resource_id");

                    b.ToTable("upload_intents", "attachments", t =>
                        {
                            t.HasCheckConstraint("ck_upload_intents_status", "status IN ('Pending', 'Uploaded', 'Active', 'Expired', 'Rejected')");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
