// <auto-generated />
using System;
using Cmms.Modules.WorkManagement.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cmms.Modules.WorkManagement.Infrastructure.Migrations
{
    [DbContext(typeof(WorkManagementDbContext))]
    [Migration("20260903174025_AddChecklistDowntimeParts")]
    partial class AddChecklistDowntimeParts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("work_management")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cmms.Modules.WorkManagement.Domain.ChecklistItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AttachmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("attachment_id");

                    b.Property<bool?>("BooleanValue")
                        .HasColumnType("boolean")
                        .HasColumnName("boolean_value");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("ExecutionCycle")
                        .HasColumnType("integer")
                        .HasColumnName("execution_cycle");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_resolved");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("item_type");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("label");

                    b.Property<string>("NoteText")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("note_text");

                    b.Property<decimal?>("NumericMaxValue")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("numeric_max_value");

                    b.Property<decimal?>("NumericMinValue")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("numeric_min_value");

                    b.Property<bool?>("NumericOutOfTolerance")
                        .HasColumnType("boolean")
                        .HasColumnName("numeric_out_of_tolerance");

                    b.Property<string>("NumericUnit")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("numeric_unit");

                    b.Property<decimal?>("NumericValue")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("numeric_value");

                    b.Property<DateTimeOffset?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at_utc");

                    b.Property<Guid?>("ResolvedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by_user_id");

                    b.Property<bool>("SafetyCritical")
                        .HasColumnType("boolean")
                        .HasColumnName("safety_critical");

                    b.Property<string>("SelectedOption")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("selected_option");

                    b.Property<string>("SingleSelectOptionsCsv")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("single_select_options_csv");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_order_id");

                    b.HasKey("Id")
                        .HasName("pk_checklist_items");

                    b.HasIndex("WorkOrderId", "ExecutionCycle")
                        .HasDatabaseName("ix_checklist_items_work_order_id_execution_cycle");

                    b.ToTable("checklist_items", "work_management", t =>
                        {
                            t.HasCheckConstraint("ck_checklist_items_item_type", "item_type IN ('Boolean', 'Numeric', 'SingleSelect', 'PhotoRequired', 'Note')");
                        });
                });

            modelBuilder.Entity("Cmms.Modules.WorkManagement.Domain.DowntimeInterval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<string>("CauseCategory")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cause_category");

                    b.Property<string>("CauseMechanism")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("cause_mechanism");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("classification");

                    b.Property<DateTimeOffset?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at_utc");

                    b.Property<int>("ExecutionCycle")
                        .HasColumnType("integer")
                        .HasColumnName("execution_cycle");

                    b.Property<Guid>("RecordedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("recorded_by_user_id");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_order_id");

                    b.HasKey("Id")
                        .HasName("pk_downtime_intervals");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("ix_downtime_intervals_asset_id");

                    b.HasIndex("WorkOrderId", "ExecutionCycle")
                        .HasDatabaseName("ix_downtime_intervals_work_order_id_execution_cycle");

                    b.ToTable("downtime_intervals", "work_management", t =>
                        {
                            t.HasCheckConstraint("ck_downtime_intervals_cause_category", "cause_category IS NULL OR cause_category IN ('Mechanical', 'Electrical', 'Hydraulic', 'Pneumatic', 'Instrumentation', 'Operational')");

                            t.HasCheckConstraint("ck_downtime_intervals_classification", "classification IN ('FullStop', 'PartialDerating')");

                            t.HasCheckConstraint("ck_downtime_intervals_ended_after_started", "ended_at_utc IS NULL OR ended_at_utc >= started_at_utc");
                        });
                });

            modelBuilder.Entity("Cmms.Modules.WorkManagement.Domain.PartUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<int>("ExecutionCycle")
                        .HasColumnType("integer")
                        .HasColumnName("execution_cycle");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("PartCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("part_code");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("part_name");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("quantity");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("unit_cost");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_order_id");

                    b.HasKey("Id")
                        .HasName("pk_part_usages");

                    b.HasIndex("WorkOrderId", "ExecutionCycle")
                        .HasDatabaseName("ix_part_usages_work_order_id_execution_cycle");

                    b.HasIndex("WorkOrderId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_part_usages_work_order_id_idempotency_key")
                        .HasFilter("idempotency_key IS NOT NULL");

                    b.ToTable("part_usages", "work_management");
                });

            modelBuilder.Entity("Cmms.Modules.WorkManagement.Domain.WorkOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<DateTimeOffset?>("AssignedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at_utc");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_id");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("cancel_reason");

                    b.Property<DateTimeOffset?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at_utc");

                    b.Property<Guid?>("CancelledByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("cancelled_by_user_id");

                    b.Property<DateTimeOffset?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at_utc");

                    b.Property<Guid?>("ClosedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("closed_by_user_id");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<Guid?>("CompletedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("completed_by_user_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<int>("ExecutionCycle")
                        .HasColumnType("integer")
                        .HasColumnName("execution_cycle");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("priority");

                    b.Property<string>("ReopenReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reopen_reason");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("row_version");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<Guid?>("SourceRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_request_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("WrenchStartAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("wrench_start_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_work_orders");

                    b.HasAlternateKey("SiteId", "Id")
                        .HasName("ak_work_orders_site_id_id");

                    b.HasIndex("AssigneeId")
                        .HasDatabaseName("ix_work_orders_assignee_id");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("ix_work_orders_site_id");

                    b.HasIndex("SourceRequestId")
                        .IsUnique()
                        .HasDatabaseName("ix_work_orders_source_request_id")
                        .HasFilter("source_request_id IS NOT NULL");

                    b.HasIndex("SiteId", "Status")
                        .HasDatabaseName("ix_work_orders_site_id_status");

                    b.ToTable("work_orders", "work_management", t =>
                        {
                            t.HasCheckConstraint("ck_work_orders_priority", "priority IN ('P1', 'P2', 'P3', 'P4')");

                            t.HasCheckConstraint("ck_work_orders_status", "status IN ('Draft', 'Open', 'Scheduled', 'InProgress', 'Completed', 'Closed', 'Cancelled')");
                        });
                });

            modelBuilder.Entity("Cmms.Modules.WorkManagement.Domain.ChecklistItem", b =>
                {
                    b.HasOne("Cmms.Modules.WorkManagement.Domain.WorkOrder", null)
                        .WithMany()
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_checklist_items_work_orders_work_order_id");
                });

            modelBuilder.Entity("Cmms.Modules.WorkManagement.Domain.DowntimeInterval", b =>
                {
                    b.HasOne("Cmms.Modules.WorkManagement.Domain.WorkOrder", null)
                        .WithMany()
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_downtime_intervals_work_orders_work_order_id");
                });

            modelBuilder.Entity("Cmms.Modules.WorkManagement.Domain.PartUsage", b =>
                {
                    b.HasOne("Cmms.Modules.WorkManagement.Domain.WorkOrder", null)
                        .WithMany()
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_part_usages_work_orders_work_order_id");
                });
#pragma warning restore 612, 618
        }
    }
}
